--- 
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0

gemfile:
  - Gemfile

notifications:
  email:
    - RoUS@redhat.com

before_install:
  - sudo apt-get update -qq
  - gem install versionomy

script:
  - bundle exec rake features
