--- 
#
# Try using the container mechanism.
#
sudo: false

#
# Package info.
#
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0

gemfile:
  - Gemfile

notifications:
  email:
    - RoUS@redhat.com

before_install:
  - gem install bundler
  - gem install versionomy

script:
  - bundle exec rake features
  - bundle exec rake yard
