--- 
#
# Try using the container mechanism.
#
sudo: false

#
# Package info.
#
language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - 2.4.0

gemfile:
  - Gemfile

notifications:
  email:
    - RoUS@redhat.com

#
# Preparing, building, and testing.
#
apt:
  update: true

before_install:
  - gem install bundler
  - gem install versionomy

script:
  - bundle exec rake features
  - bundle exec rake yard
